### ISSUE TITLE
Problem of packaging using ros-melodic

### ISSUE THREAD

**Issue by MaximilienNaveau** [humanoid-path-planner/hpp-fcl-ros-release#1]
Hi @wxmerkt ,

@nim65s told me you where and actor of these releases.
I am trying to use [hpp-afforadcne](https://github.com/humanoid-path-planner/hpp-affordance) under ferrum which means Ubuntu18.04/ROS melodic.

I have an issue with hpp-fcl being too old on ros-melodic and the (std vs boost) shared pointer issue makes the binaries incompatible. Would it be possible to upgrade the package?

How can I help doing that?

**Comment by nim65s** [comment]
@MaximilienNaveau : btw, if you're taking hpp-affordance binaries from robotpkg and hpp-fcl binaries from ROS, you'll have troubles ;)

**Comment by MaximilienNaveau** [comment]
@nim65s for now I am building hpp-affordance from source as I do not use robotpkg in my particular setting

@wxmerkt I am sorry I think the release has been made in melodic and that my OS is outdated. I will try to figure that out.
